# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 01:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xena', '0005_remove_view_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='comments',
            field=models.ManyToManyField(through='xena.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
